import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT||3000);
const APP_URL=process.env.APP_URL||`http://localhost:${PORT}`;
const BRAND_NAME=process.env.BRAND_NAME||'NutriPilot';
const OPENAI_API_KEY=process.env.OPENAI_API_KEY||'';
const OPENAI_MODEL=process.env.OPENAI_MODEL||'';
const TRIAL_DAYS=Number(process.env.TRIAL_DAYS??0);
const SUPPORT_EMAIL=process.env.SUPPORT_EMAIL||'support@atlasevermore.com';
const ACCESS_TOKEN_SECRET=process.env.ACCESS_TOKEN_SECRET||process.env.HOTMART_HOTTOK||(process.env.NODE_ENV==='development'?'dev-only-change-me':'');
const DATA_DIR=path.join(__dirname,'data');
const ENTITLEMENTS_FILE=path.join(DATA_DIR,'entitlements.json');
const LAST_WEBHOOK_FILE=path.join(DATA_DIR,'last-webhook.json');

const TYPES={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.ico':'image/x-icon'};
const prices={monthly:process.env.PRICE_MONTHLY||'9.90',quarterly:process.env.PRICE_QUARTERLY||'19.90',yearly:process.env.PRICE_YEARLY||'39.90'};
const DEFAULT_HOTMART_CHECKOUTS={
  monthly:'https://pay.hotmart.com/R107884011S?off=r3ueswug',
  quarterly:'https://pay.hotmart.com/R107884011S?off=xb98vzl6',
  yearly:'https://pay.hotmart.com/R107884011S?off=gatqnh54'
};
const checkouts={monthly:process.env.HOTMART_CHECKOUT_MONTHLY||DEFAULT_HOTMART_CHECKOUTS.monthly,quarterly:process.env.HOTMART_CHECKOUT_QUARTERLY||DEFAULT_HOTMART_CHECKOUTS.quarterly,yearly:process.env.HOTMART_CHECKOUT_YEARLY||DEFAULT_HOTMART_CHECKOUTS.yearly};
const HOTMART_OFFER_TO_PLAN={r3ueswug:'monthly',xb98vzl6:'quarterly',gatqnh54:'yearly'};

function headers(type='application/json; charset=utf-8'){
  return {'Content-Type':type,'Cache-Control':type.includes('json')?'no-store':'public, max-age=180','X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(self), microphone=(self), geolocation=()','Cross-Origin-Opener-Policy':'same-origin-allow-popups'};
}
function send(res,status,body,type){const t=type||'application/json; charset=utf-8';res.writeHead(status,headers(t));res.end(Buffer.isBuffer(body)?body:(typeof body==='string'?body:JSON.stringify(body)));}
async function readRaw(req,limit=14_000_000){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>limit)throw new Error('Payload trop volumineux');}return raw;}
async function readJson(req){const raw=await readRaw(req);return raw?JSON.parse(raw):{};}
function safeEmail(v=''){const x=String(v).trim().toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)?x:'';}
function csv(v=''){return String(v).split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);}
function deepFind(obj,keyNames){const keys=new Set(keyNames.map(x=>x.toLowerCase()));const seen=new Set();function walk(x){if(!x||typeof x!=='object'||seen.has(x))return null;seen.add(x);for(const [k,v] of Object.entries(x)){if(keys.has(k.toLowerCase())&&typeof v==='string'&&v.trim())return v.trim();}for(const v of Object.values(x)){const got=walk(v);if(got)return got;}return null;}return walk(obj);}
async function ensureData(){await fs.mkdir(DATA_DIR,{recursive:true});try{await fs.access(ENTITLEMENTS_FILE)}catch{await fs.writeFile(ENTITLEMENTS_FILE,'{}','utf8')}}
async function loadEntitlements(){await ensureData();try{return JSON.parse(await fs.readFile(ENTITLEMENTS_FILE,'utf8'))}catch{return {}}}
async function saveEntitlements(d){await ensureData();await fs.writeFile(ENTITLEMENTS_FILE,JSON.stringify(d,null,2),'utf8')}
function safeTokenEqual(a,b){const aa=Buffer.from(String(a||'')),bb=Buffer.from(String(b||''));return aa.length===bb.length&&aa.length>0&&crypto.timingSafeEqual(aa,bb)}
function verifyHotmartWebhook(req){const secret=process.env.HOTMART_HOTTOK||'';const allowUnsigned=String(process.env.HOTMART_WEBHOOK_ALLOW_UNSIGNED||'false').toLowerCase()==='true';if(!secret)return allowUnsigned;const received=String(req.headers['x-hotmart-hottok']||'').trim();return safeTokenEqual(received,secret)}
function eventName(payload){return String(payload?.event||deepFind(payload,['event','event_name','type','status','name'])||'').toUpperCase()}
function buyerEmail(payload){return safeEmail(payload?.data?.buyer?.email||payload?.data?.subscriber?.email||deepFind(payload,['email','buyer_email','customer_email','payer_email','subscriber_email','user_email'])||'')}
function orderId(payload){return String(payload?.data?.purchase?.transaction||payload?.id||deepFind(payload,['transaction','order_id','transaction_id','purchase_id','id','subscription_id'])||'').slice(0,160)}
function planFrom(payload){const offerCode=String(payload?.data?.purchase?.offer?.code||payload?.data?.offer?.code||deepFind(payload,['offer_code','offerCode'])||'').trim().toLowerCase();if(HOTMART_OFFER_TO_PLAN[offerCode])return HOTMART_OFFER_TO_PLAN[offerCode];const raw=String(payload?.data?.subscription?.plan?.name||payload?.data?.purchase?.offer?.name||deepFind(payload,['plan','offer','product','product_name','plan_name'])||'').toLowerCase();if(raw.includes('year')||raw.includes('annuel')||raw.includes('annual'))return'yearly';if(raw.includes('3 mois')||raw.includes('quarter')||raw.includes('trimes'))return'quarterly';if(raw.includes('month')||raw.includes('mensuel')||raw.includes('mens'))return'monthly';return'premium'}
function accessUntilFromHotmart(payload){const n=Number(payload?.data?.purchase?.date_next_charge||0);return Number.isFinite(n)&&n>0?n:null}
function subscriptionCode(payload){return String(payload?.data?.subscription?.subscriber?.code||payload?.data?.subscriber_code||deepFind(payload,['subscriber_code'])||'').slice(0,120)}

const foods=[
 {n:'Œuf',k:143,p:12.6,c:0.7,f:9.5,fi:0},{n:'Pain complet',k:247,p:13,c:41,f:4.2,fi:7},{n:'Avocat',k:160,p:2,c:8.5,f:14.7,fi:6.7},{n:'Poulet grillé',k:165,p:31,c:0,f:3.6,fi:0},{n:'Riz cuit',k:130,p:2.7,c:28,f:.3,fi:.4},{n:'Pâtes cuites',k:158,p:5.8,c:31,f:.9,fi:1.8},{n:'Saumon',k:208,p:20,c:0,f:13,fi:0},{n:'Thon au naturel',k:116,p:26,c:0,f:1,fi:0},{n:'Yaourt grec',k:97,p:9,c:3.9,f:5,fi:0},{n:'Fromage blanc 0%',k:46,p:8,c:4,f:.2,fi:0},{n:'Banane',k:89,p:1.1,c:23,f:.3,fi:2.6},{n:'Pomme',k:52,p:.3,c:14,f:.2,fi:2.4},{n:'Pizza margherita',k:266,p:11,c:33,f:10,fi:2.3},{n:'Steak haché 5%',k:137,p:21,c:0,f:5,fi:0},{n:'Tofu',k:144,p:17,c:2.8,f:8.7,fi:2.3},{n:'Lentilles cuites',k:116,p:9,c:20,f:.4,fi:8},{n:'Pois chiches cuits',k:164,p:8.9,c:27,f:2.6,fi:7.6},{n:'Quinoa cuit',k:120,p:4.4,c:21,f:1.9,fi:2.8},{n:'Brocoli',k:35,p:2.4,c:7.2,f:.4,fi:3.3},{n:'Courgette',k:17,p:1.2,c:3.1,f:.3,fi:1},{n:'Tomate',k:18,p:.9,c:3.9,f:.2,fi:1.2},{n:'Carotte',k:41,p:.9,c:10,f:.2,fi:2.8},{n:'Flocons d’avoine',k:389,p:16.9,c:66.3,f:6.9,fi:10.6},{n:'Amandes',k:579,p:21,c:22,f:50,fi:12.5},{n:'Huile d’olive',k:884,p:0,c:0,f:100,fi:0},{n:'Beurre',k:717,p:.9,c:.1,f:81,fi:0},{n:'Emmental',k:380,p:28,c:.5,f:29,fi:0},{n:'Mozzarella',k:280,p:28,c:3.1,f:17,fi:0},{n:'Jambon blanc',k:116,p:20,c:1,f:4,fi:0},{n:'Dinde',k:135,p:30,c:0,f:1.5,fi:0},{n:'Crevettes',k:99,p:24,c:.2,f:.3,fi:0},{n:'Patate douce cuite',k:90,p:2,c:21,f:.2,fi:3.3},{n:'Pomme de terre cuite',k:87,p:1.9,c:20,f:.1,fi:1.8},{n:'Fraises',k:32,p:.7,c:7.7,f:.3,fi:2},{n:'Myrtilles',k:57,p:.7,c:14.5,f:.3,fi:2.4},{n:'Orange',k:47,p:.9,c:12,f:.1,fi:2.4},{n:'Chocolat noir 70%',k:598,p:7.8,c:46,f:43,fi:11},{n:'Baguette',k:270,p:9,c:57,f:1,fi:2.7},{n:'Croissant',k:406,p:8,c:46,f:21,fi:2.6},{n:'Skyr',k:63,p:11,c:4,f:.2,fi:0}
];

function normalizeText(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function localAnalyze(text=''){
 const low=normalizeText(text);
 const found=[];
 for(const food of foods){
  const key=normalizeText(food.n).split(' ')[0];
  if(!low.includes(key))continue;
  let grams=100;
  const escaped=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
  const directBefore=low.match(new RegExp(`(\\d{1,4})\\s?g\\s*(?:de|du|des|d')?\\s*${escaped}`,'i'));
  const directAfter=low.match(new RegExp(`${escaped}\\s*(?:[:=-]?\\s*)?(\\d{1,4})\\s?g`,'i'));
  if(directBefore||directAfter) grams=Number((directBefore&&directBefore[1])||(directAfter&&directAfter[1]));
  else if(key==='oeuf'){const count=low.match(/(\d{1,2})\s*(?:oeuf|oeufs)/);grams=count?Number(count[1])*50:100;}
  const q=grams/100;
  found.push({name:food.n,grams,kcal:Math.round(food.k*q),protein:+(food.p*q).toFixed(1),carbs:+(food.c*q).toFixed(1),fat:+(food.f*q).toFixed(1),fiber:+(food.fi*q).toFixed(1),confidence:.68});
 }
 if(!found.length)found.push({name:text||'Repas à confirmer',grams:300,kcal:420,protein:24,carbs:44,fat:16,fiber:6,confidence:.35});
 const total=found.reduce((a,x)=>({kcal:a.kcal+x.kcal,protein:a.protein+x.protein,carbs:a.carbs+x.carbs,fat:a.fat+x.fat,fiber:a.fiber+x.fiber}),{kcal:0,protein:0,carbs:0,fat:0,fiber:0});
 Object.keys(total).forEach(k=>total[k]=k==='kcal'?Math.round(total[k]):+total[k].toFixed(1));
 const conf=Math.min(...found.map(x=>x.confidence));
 return{title:text?'Repas analysé':'Photo à confirmer',foods:found,total,confidence:conf,range:{min:Math.max(0,Math.round(total.kcal*(1-(1-conf)*.5))),max:Math.round(total.kcal*(1+(1-conf)*.7))},assumptions:['Les portions visibles sont estimées.','Les huiles, sauces et ingrédients cachés peuvent modifier le total.'],note:'Vérifiez les aliments et ajustez les grammes avant d’enregistrer.',source:'fallback'};
}
function outputText(data){if(typeof data?.output_text==='string')return data.output_text;const out=[];for(const item of data?.output||[])for(const c of item?.content||[])if(typeof c?.text==='string')out.push(c.text);return out.join('\n')}
function parseJson(text=''){try{return JSON.parse(text)}catch{}const m=String(text).match(/\{[\s\S]*\}/);if(!m)throw new Error('Réponse IA illisible');return JSON.parse(m[0])}
async function callAI(input,max=1600){if(!OPENAI_API_KEY||!OPENAI_MODEL)throw new Error('IA non configurée');const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:OPENAI_MODEL,input,max_output_tokens:max})});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'Erreur IA');return parseJson(outputText(d));}
async function aiAnalyze({text='',image='',mode='meal'}){if(!OPENAI_API_KEY||!OPENAI_MODEL)return localAnalyze(text);const prompt=`Tu es un assistant de suivi nutritionnel en français. Mode: ${mode}. Analyse le repas/étiquette sans prétendre à une précision impossible. Une photo ne permet pas de peser les portions; exprime l'incertitude. Retourne UNIQUEMENT JSON valide: {"title":"...","foods":[{"name":"...","grams":120,"kcal":200,"protein":10,"carbs":20,"fat":8,"fiber":3,"confidence":0.75}],"total":{"kcal":200,"protein":10,"carbs":20,"fat":8,"fiber":3},"confidence":0.75,"range":{"min":170,"max":240},"assumptions":["..."],"note":"..."}. Texte utilisateur: ${text||'(aucun)'}`;const content=[{type:'input_text',text:prompt}];if(image)content.push({type:'input_image',image_url:image,detail:'high'});const d=await callAI([{role:'user',content}],1800);d.source='ai';return d;}
async function compose(body){const remaining=Math.max(180,Math.min(1800,Number(body.remaining||500)));if(!OPENAI_API_KEY||!OPENAI_MODEL)return{source:'fallback',options:[{name:'Assiette méditerranéenne',kcal:Math.min(remaining,480),protein:38,carbs:46,fat:15,fiber:9,prep:'15 min',ingredients:['Poulet ou tofu','Pommes de terre','Courgettes','Tomates','Yaourt citronné'],why:'Bon volume, protéines et fibres.'},{name:'Pâtes plaisir équilibrées',kcal:Math.min(remaining,520),protein:34,carbs:62,fat:12,fiber:8,prep:'15 min',ingredients:['Pâtes','Thon ou lentilles','Sauce tomate','Épinards'],why:'Garde le plat envie avec une portion cadrée.'},{name:'Bol frais express',kcal:Math.min(remaining,440),protein:30,carbs:48,fat:13,fiber:11,prep:'10 min',ingredients:['Riz ou quinoa','Saumon ou tofu','Concombre','Carotte','Edamame'],why:'Simple, rassasiant et adaptable.'}]};const input=`Crée 3 repas réalistes en France pour environ ${remaining} kcal maximum. Préférence: ${body.preference||'aucune'}. Envie: ${body.craving||'libre'}. Éviter/allergies: ${body.avoid||'aucun'}. Temps disponible: ${body.cooking||'libre'}. Retourne UNIQUEMENT JSON: {"options":[{"name":"...","kcal":450,"protein":30,"carbs":45,"fat":15,"fiber":8,"prep":"15 min","ingredients":["..."],"why":"..."}]}. Valeurs = estimations générales.`;const d=await callAI(input,1400);d.source='ai';return d;}
async function coach(body){const context=JSON.stringify({goal:body.goal,dailyKcal:body.dailyKcal,remaining:body.remaining,proteinLeft:body.proteinLeft,diet:body.diet,allergies:body.allergies});if(!OPENAI_API_KEY||!OPENAI_MODEL)return{answer:'Je peux vous aider à transformer votre objectif du jour en choix concrets. En mode démo, utilisez « Composer mon repas » ou ajoutez une clé IA pour des réponses personnalisées. Les estimations ne remplacent pas un professionnel de santé.'};const input=`Tu es le coach nutritionnel de NutriPilot. Réponds en français, brièvement, sans diagnostic ni prescription médicale. Aide à faire des choix alimentaires pragmatiques, sans culpabiliser ni promouvoir des restrictions extrêmes. Contexte: ${context}. Question: ${body.message}. Si grossesse, trouble alimentaire, maladie, médicament ou symptôme médical, recommande un professionnel adapté. Retourne UNIQUEMENT JSON: {"answer":"..."}.`;return await callAI(input,800)}
async function barcode(code){if(!/^\d{8,14}$/.test(code))throw new Error('Code-barres invalide');const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json?fields=product_name,brands,nutriments,serving_size,image_front_small_url`);const d=await r.json();if(!r.ok||!d?.product)throw new Error('Produit introuvable');const n=d.product.nutriments||{};const item={name:d.product.product_name||d.product.brands||'Produit',grams:100,kcal:Number(n['energy-kcal_100g']||0),protein:Number(n.proteins_100g||0),carbs:Number(n.carbohydrates_100g||0),fat:Number(n.fat_100g||0),fiber:Number(n.fiber_100g||0),confidence:.95};return{title:item.name,foods:[item],total:{kcal:Math.round(item.kcal),protein:+item.protein.toFixed(1),carbs:+item.carbs.toFixed(1),fat:+item.fat.toFixed(1),fiber:+item.fiber.toFixed(1)},confidence:.95,range:{min:Math.round(item.kcal*.95),max:Math.round(item.kcal*1.05)},assumptions:['Valeurs pour 100 g selon la base Open Food Facts.'],note:'Ajustez la quantité réellement consommée.',source:'openfoodfacts',image:d.product.image_front_small_url||''};}

function signAccessToken(email){if(!ACCESS_TOKEN_SECRET)throw new Error('ACCESS_TOKEN_SECRET manquant');const now=Math.floor(Date.now()/1000),payload={email,iat:now,exp:now+60*60*24*45};const body=Buffer.from(JSON.stringify(payload)).toString('base64url');const sig=crypto.createHmac('sha256',ACCESS_TOKEN_SECRET).update(body).digest('base64url');return `${body}.${sig}`;}
function verifyAccessToken(token=''){if(!ACCESS_TOKEN_SECRET)return null;const [body,sig]=String(token).split('.');if(!body||!sig)return null;const expected=crypto.createHmac('sha256',ACCESS_TOKEN_SECRET).update(body).digest('base64url');try{if(!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;}catch{return null}try{const p=JSON.parse(Buffer.from(body,'base64url').toString('utf8'));if(!p.email||Number(p.exp||0)<Math.floor(Date.now()/1000))return null;return p}catch{return null}}

async function sendAccessEmail(email,code){const key=process.env.RESEND_API_KEY||'';if(!key)return false;const from=process.env.RESEND_FROM||`${BRAND_NAME} <onboarding@resend.dev>`;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[email],subject:`Votre code d’accès ${BRAND_NAME}`,html:`<div style="font-family:Arial,sans-serif"><h2>${BRAND_NAME}</h2><p>Votre code d’accès est :</p><p style="font-size:28px;font-weight:800;letter-spacing:4px">${code}</p><p>Entrez ce code dans l’application. Si vous n’êtes pas à l’origine de cet achat, ignorez cet e-mail.</p></div>`})});return r.ok;}
async function requestAccessCode(email){const ent=await loadEntitlements();const e=ent[email];if(!e||e.status!=='active')return{ok:false};const code=String(Math.floor(100000+Math.random()*900000));e.codeHash=crypto.createHash('sha256').update(code).digest('hex');e.codeExpiresAt=Date.now()+15*60*1000;ent[email]=e;await saveEntitlements(ent);const mailed=await sendAccessEmail(email,code);return{ok:true,mailed,devCode:process.env.NODE_ENV==='development'&&!mailed?code:undefined};}
async function verifyAccessCode(email,code){const ent=await loadEntitlements();const e=ent[email];if(!e||e.status!=='active'||!e.codeHash||Date.now()>Number(e.codeExpiresAt||0))return false;const h=crypto.createHash('sha256').update(String(code)).digest('hex');if(h!==e.codeHash)return false;delete e.codeHash;delete e.codeExpiresAt;e.lastActivatedAt=new Date().toISOString();ent[email]=e;await saveEntitlements(ent);return true;}

const server=http.createServer(async(req,res)=>{try{
 const url=new URL(req.url,APP_URL);
 if(url.pathname==='/api/config'&&req.method==='GET')return send(res,200,{brand:BRAND_NAME,locale:'fr-FR',ai:Boolean(OPENAI_API_KEY&&OPENAI_MODEL),trialDays:TRIAL_DAYS,prices,checkoutConfigured:Object.fromEntries(Object.entries(checkouts).map(([k,v])=>[k,Boolean(v)])),supportEmail:SUPPORT_EMAIL,manageSubscriptionUrl:process.env.HOTMART_MANAGE_SUBSCRIPTION_URL||'https://consumer.hotmart.com/',legal:{company:process.env.LEGAL_COMPANY_NAME||'',address:process.env.LEGAL_COMPANY_ADDRESS||'',id:process.env.LEGAL_COMPANY_ID||''}});
 if(url.pathname==='/api/health')return send(res,200,{ok:true,brand:BRAND_NAME,ai:Boolean(OPENAI_API_KEY&&OPENAI_MODEL),hotmart:Boolean(checkouts.monthly||checkouts.quarterly||checkouts.yearly)});
 if(url.pathname==='/api/analyze'&&req.method==='POST')return send(res,200,await aiAnalyze(await readJson(req)));
 if(url.pathname==='/api/compose'&&req.method==='POST')return send(res,200,await compose(await readJson(req)));
 if(url.pathname==='/api/coach'&&req.method==='POST')return send(res,200,await coach(await readJson(req)));
 if(url.pathname==='/api/barcode'&&req.method==='GET')return send(res,200,await barcode(url.searchParams.get('code')||''));
 if(url.pathname==='/api/checkout'&&req.method==='POST'){const b=await readJson(req);const plan=['monthly','quarterly','yearly'].includes(b.plan)?b.plan:'yearly';const target=checkouts[plan];if(!target)return send(res,503,{error:`Checkout Hotmart non configuré pour ${plan}.`});let dest=new URL(target);for(const k of ['utm_source','utm_medium','utm_campaign','utm_content','utm_term'])if(b[k])dest.searchParams.set(k,String(b[k]).slice(0,180));return send(res,200,{url:dest.toString(),plan,price:prices[plan]});}
 if(url.pathname==='/api/hotmart/webhook'&&req.method==='POST'){const raw=await readRaw(req);let payload={};try{payload=raw?JSON.parse(raw):{}}catch{return send(res,400,{error:'JSON invalide'})}await ensureData();await fs.writeFile(LAST_WEBHOOK_FILE,JSON.stringify({receivedAt:new Date().toISOString(),headers:{'user-agent':req.headers['user-agent']||'','x-hotmart-hottok':req.headers['x-hotmart-hottok']?'present':'missing'},payload},null,2),'utf8');if(!verifyHotmartWebhook(req))return send(res,401,{error:'Hottok Hotmart invalide. Consultez HOTMART_SETUP.md.'});const event=eventName(payload);const email=buyerEmail(payload);if(!email)return send(res,422,{error:'Email acheteur introuvable dans le payload Hotmart'});const approved=new Set(['PURCHASE_APPROVED','PURCHASE_COMPLETE']);const revoked=new Set(['PURCHASE_REFUNDED','PURCHASE_CHARGEBACK','PURCHASE_CANCELED']);const ent=await loadEntitlements();if(approved.has(event)){ent[email]={status:'active',plan:planFrom(payload),orderId:orderId(payload),subscriberCode:subscriptionCode(payload),accessUntil:accessUntilFromHotmart(payload),event,updatedAt:new Date().toISOString()};await saveEntitlements(ent);return send(res,200,{ok:true,action:'granted'})}if(event==='SUBSCRIPTION_CANCELLATION'){const prev=ent[email]||{};ent[email]={...prev,status:prev.accessUntil&&Date.now()<Number(prev.accessUntil)?'active':'revoked',cancelAtPeriodEnd:true,event,updatedAt:new Date().toISOString()};await saveEntitlements(ent);return send(res,200,{ok:true,action:ent[email].status==='active'?'cancel_at_period_end':'revoked'})}if(revoked.has(event)){ent[email]={...(ent[email]||{}),status:'revoked',event,updatedAt:new Date().toISOString()};await saveEntitlements(ent);return send(res,200,{ok:true,action:'revoked'})}if(event==='PURCHASE_DELAYED'){ent[email]={...(ent[email]||{}),paymentStatus:'delayed',event,updatedAt:new Date().toISOString()};await saveEntitlements(ent);return send(res,200,{ok:true,action:'flagged_delayed'})}return send(res,200,{ok:true,action:'ignored',event});}
 if(url.pathname==='/api/access/request'&&req.method==='POST'){const b=await readJson(req);const email=safeEmail(b.email);if(!email)return send(res,400,{error:'Email invalide'});const result=await requestAccessCode(email);if(!result.ok)return send(res,404,{error:'Aucun achat actif trouvé pour cet e-mail.'});return send(res,200,{ok:true,mailed:result.mailed,devCode:result.devCode});}
 if(url.pathname==='/api/access/verify'&&req.method==='POST'){const b=await readJson(req);const email=safeEmail(b.email);if(!email||!/^[0-9]{6}$/.test(String(b.code||'')))return send(res,400,{error:'Données invalides'});const ok=await verifyAccessCode(email,String(b.code));if(!ok)return send(res,401,{error:'Code invalide ou expiré'});return send(res,200,{ok:true,premium:true,email,token:signAccessToken(email)});}
 if(url.pathname==='/api/access/status'&&req.method==='POST'){const b=await readJson(req);const p=verifyAccessToken(b.token||'');if(!p)return send(res,401,{premium:false,error:'Session Premium invalide ou expirée'});const ent=await loadEntitlements();const e=ent[p.email];if(e?.status==='active'&&e?.accessUntil&&Date.now()>Number(e.accessUntil)){e.status='revoked';e.event='LOCAL_ACCESS_PERIOD_ENDED';e.updatedAt=new Date().toISOString();await saveEntitlements(ent)}return send(res,200,{premium:Boolean(e&&e.status==='active'),email:p.email,plan:e?.plan||'',status:e?.status||'missing',cancelAtPeriodEnd:Boolean(e?.cancelAtPeriodEnd)});}
 let requested=decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname);let filePath=path.join(__dirname,requested);if(!filePath.startsWith(__dirname))return send(res,403,'Forbidden','text/plain');try{const stat=await fs.stat(filePath);if(stat.isDirectory())filePath=path.join(filePath,'index.html');const buf=await fs.readFile(filePath);return send(res,200,buf,TYPES[path.extname(filePath)]||'application/octet-stream')}catch{const html=await fs.readFile(path.join(__dirname,'index.html'));return send(res,200,html,'text/html; charset=utf-8')}
}catch(err){console.error(err);return send(res,500,{error:err.message||'Erreur serveur'})}});
server.listen(PORT,()=>console.log(`${BRAND_NAME} v3 Hotmart — ${APP_URL}`));
